version: '3'
services:

  nginx:
    build: ./.docker/nginx-php
    restart: "no"
    depends_on:
      - php
    ports :
      - "${NGINX_PORT}:80"
    environment:
      - "SERVER_NAME=${SERVER_NAME}"
      - "PHP_ADDRESS=${PHP_ADDRESS}"
      - "TZ=${TIMEZONE}"
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - "ensiie"

  php:
    build:
      context: ./.docker/php-fpm/
      args:
        DOCKER_USER: ${DOCKER_USER}
        DOCKER_USER_ID: ${DOCKER_USER_ID}
    restart: "no"
    environment:
      TZ: ${TIMEZONE}
      XDEBUG_CONFIG: remote_host=${REMOTE_HOST}
      SSH_AUTH_SOCK: /ssh-agent
      DB_NAME: 'projet'
      DB_USER: 'root'
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./:/var/www/html
      # - /run/user/1000/keyring/ssh:/ssh-agent
    working_dir: /var/www/html
    user: "${DOCKER_USER}"
    entrypoint:
      - ""
    command:
      - "php-fpm"
    networks:
      - "ensiie"

  mysql:
    build:
      context: ./.docker/mysql
    ports:
      - "${DB_PORT_EXTERNAL}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db-data:/var/lib/mysql
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - "ensiie"
  
  phpmyadmin:
    depends_on:
      - mysql
    build:
      context: ./.docker/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - ensiie

networks:
    ensiie:
        driver: bridge
